-- Direct bookings become visible in /cabinet «Записи» the same way guest
-- requests are.
--
-- Cause: requests carry (public_ref, guest_token); the browser remembers the
-- pair, the cabinet reads status with it, and sign-in links the request to the
-- account. Bookings had neither column, so a direct booking left nothing to
-- remember or prove ownership with, and never showed.
--
-- 1. bookings.public_ref (unique) + bookings.guest_token (64 hex chars), both
--    generated by the database, the same way requests do it. Existing rows get
--    their own values that nobody holds — harmless.
--    Guests never read bookings directly: anon has no SELECT policy. A server
--    action reads a booking only for an exact (public_ref, guest_token) pair and
--    returns non-contact fields, so bookings can't be listed or guessed.
-- 2. bookings_update no longer lets the customer change their own row (it let
--    them set status = 'confirmed'). No feature needs it; only an admin or the
--    provider changes a booking. Sign-in now sets customer_id on direct
--    bookings, which would have made that hole reachable.

alter table public.bookings
  add column public_ref text not null default upper(substr(md5(gen_random_uuid()::text), 1, 10)),
  add column guest_token text not null default (md5(gen_random_uuid()::text) || md5(gen_random_uuid()::text));

alter table public.bookings
  add constraint bookings_public_ref_key unique (public_ref);

comment on column public.bookings.public_ref is 'Public booking reference shown to the guest; with guest_token it is the read key.';
comment on column public.bookings.guest_token is 'Secret read key held by the guest''s browser (never shown to providers).';

drop policy bookings_update on public.bookings;
create policy bookings_update on public.bookings
  for update using (public.is_admin() or public.is_provider_member(provider_id))
  with check (public.is_admin() or public.is_provider_member(provider_id));
